// <auto-generated />
using System;
using Klyvesta.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Klyvesta.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KlyvestaDbContext))]
    [Migration("20260825183500_F5SecuritySessionPersistence")]
    partial class F5SecuritySessionPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Klyvesta.Infrastructure.Persistence.Records.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<DateTimeOffset?>("CompletedAt").HasColumnType("timestamp with time zone").HasColumnName("completed_at");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<DateTimeOffset>("ExpiresAt").HasColumnType("timestamp with time zone").HasColumnName("expires_at");
                    b.Property<string>("Key").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("key");
                    b.Property<Guid?>("OperationId").HasColumnType("uuid").HasColumnName("operation_id");
                    b.Property<string>("RequestHash").IsRequired().HasColumnType("character(64)").HasColumnName("request_hash");
                    b.Property<string>("Scope").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("scope");
                    b.Property<string>("State").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("state");
                    b.HasKey("Id").HasName("pk_idempotency_record");
                    b.HasIndex("ExpiresAt").HasDatabaseName("ix_idempotency_record_expires_at");
                    b.HasIndex("Scope", "Key").IsUnique().HasDatabaseName("ux_idempotency_record_scope_key");
                    b.ToTable("idempotency_record", "ops", t =>
                        {
                            t.HasCheckConstraint("ck_idempotency_record_completion_chronology", "completed_at IS NULL OR completed_at >= created_at");
                            t.HasCheckConstraint("ck_idempotency_record_expiry", "expires_at > created_at");
                            t.HasCheckConstraint("ck_idempotency_record_state", "state IN ('in_progress', 'completed', 'failed')");
                        });
                });

            modelBuilder.Entity("Klyvesta.Infrastructure.Persistence.Records.InboxMessage", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<string>("MessageId").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("message_id");
                    b.Property<string>("PayloadHash").IsRequired().HasColumnType("character(64)").HasColumnName("payload_hash");
                    b.Property<string>("PayloadJson").IsRequired().HasColumnType("jsonb").HasColumnName("payload_json");
                    b.Property<DateTimeOffset?>("ProcessedAt").HasColumnType("timestamp with time zone").HasColumnName("processed_at");
                    b.Property<string>("Provider").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("provider");
                    b.Property<DateTimeOffset>("ReceivedAt").HasColumnType("timestamp with time zone").HasColumnName("received_at");
                    b.Property<string>("State").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("state");
                    b.HasKey("Id").HasName("pk_inbox_message");
                    b.HasIndex("Provider", "MessageId").IsUnique().HasDatabaseName("ux_inbox_message_provider_message_id");
                    b.HasIndex("State", "ReceivedAt").HasDatabaseName("ix_inbox_message_state_received_at");
                    b.ToTable("inbox_message", "ops", t =>
                        {
                            t.HasCheckConstraint("ck_inbox_message_processing_chronology", "processed_at IS NULL OR processed_at >= received_at");
                            t.HasCheckConstraint("ck_inbox_message_state", "state IN ('received', 'processing', 'processed', 'failed')");
                        });
                });

            modelBuilder.Entity("Klyvesta.Infrastructure.Persistence.Records.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<int>("AttemptCount").HasColumnType("integer").HasColumnName("attempt_count");
                    b.Property<string>("EventType").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("event_type");
                    b.Property<string>("HeadersJson").HasColumnType("jsonb").HasColumnName("headers_json");
                    b.Property<string>("LastErrorCode").HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("last_error_code");
                    b.Property<DateTimeOffset?>("NextAttemptAt").HasColumnType("timestamp with time zone").HasColumnName("next_attempt_at");
                    b.Property<DateTimeOffset>("OccurredAt").HasColumnType("timestamp with time zone").HasColumnName("occurred_at");
                    b.Property<string>("PayloadJson").IsRequired().HasColumnType("jsonb").HasColumnName("payload_json");
                    b.Property<DateTimeOffset?>("PublishedAt").HasColumnType("timestamp with time zone").HasColumnName("published_at");
                    b.HasKey("Id").HasName("pk_outbox");
                    b.HasIndex("NextAttemptAt", "OccurredAt").HasDatabaseName("ix_outbox_pending").HasFilter("published_at IS NULL");
                    b.ToTable("outbox", "notification", t =>
                        {
                            t.HasCheckConstraint("ck_outbox_attempt_count", "attempt_count >= 0");
                        });
                });

            modelBuilder.Entity("Klyvesta.Infrastructure.Persistence.Records.SecurityDeviceRecord", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<string>("IntegrityState").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("integrity_state");
                    b.Property<DateTimeOffset>("LastSeenAt").HasColumnType("timestamp with time zone").HasColumnName("last_seen_at");
                    b.Property<Guid>("PrincipalId").HasColumnType("uuid").HasColumnName("principal_id");
                    b.Property<string>("PrincipalType").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("principal_type");
                    b.Property<DateTimeOffset>("RegisteredAt").HasColumnType("timestamp with time zone").HasColumnName("registered_at");
                    b.Property<DateTimeOffset?>("RestrictedAt").HasColumnType("timestamp with time zone").HasColumnName("restricted_at");
                    b.Property<string>("RestrictionReason").HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("restriction_reason");
                    b.Property<DateTimeOffset?>("RevokedAt").HasColumnType("timestamp with time zone").HasColumnName("revoked_at");
                    b.Property<string>("RevocationReason").HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("revocation_reason");
                    b.Property<string>("TrustState").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("trust_state");
                    b.HasKey("Id").HasName("pk_security_device");
                    b.HasAlternateKey("Id", "PrincipalId", "PrincipalType").HasName("ak_security_device_identity");
                    b.HasIndex("LastSeenAt").HasDatabaseName("ix_security_device_last_seen_at");
                    b.HasIndex("PrincipalId", "TrustState").HasDatabaseName("ix_security_device_principal_state");
                    b.ToTable("security_device", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_security_device_integrity_state", "integrity_state IN ('unknown', 'meets_baseline', 'degraded', 'failed')");
                            t.HasCheckConstraint("ck_security_device_last_seen_chronology", "last_seen_at >= registered_at");
                            t.HasCheckConstraint("ck_security_device_principal_type", "principal_type IN ('customer', 'staff', 'service')");
                            t.HasCheckConstraint("ck_security_device_restriction_chronology", "restricted_at IS NULL OR restricted_at >= registered_at");
                            t.HasCheckConstraint("ck_security_device_restriction_pair", "(restricted_at IS NULL AND restriction_reason IS NULL) OR (restricted_at IS NOT NULL AND restriction_reason IS NOT NULL)");
                            t.HasCheckConstraint("ck_security_device_revocation_chronology", "revoked_at IS NULL OR revoked_at >= registered_at");
                            t.HasCheckConstraint("ck_security_device_revocation_pair", "(revoked_at IS NULL AND revocation_reason IS NULL) OR (revoked_at IS NOT NULL AND revocation_reason IS NOT NULL)");
                            t.HasCheckConstraint("ck_security_device_state_evidence", "(trust_state IN ('untrusted', 'trusted') AND restricted_at IS NULL AND revoked_at IS NULL) OR (trust_state = 'restricted' AND restricted_at IS NOT NULL AND revoked_at IS NULL) OR (trust_state = 'revoked' AND revoked_at IS NOT NULL)");
                            t.HasCheckConstraint("ck_security_device_transition_chronology", "restricted_at IS NULL OR revoked_at IS NULL OR revoked_at >= restricted_at");
                            t.HasCheckConstraint("ck_security_device_trust_state", "trust_state IN ('untrusted', 'trusted', 'restricted', 'revoked')");
                        });
                });

            modelBuilder.Entity("Klyvesta.Infrastructure.Persistence.Records.SecuritySessionRecord", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<DateTimeOffset>("AbsoluteExpiresAt").HasColumnType("timestamp with time zone").HasColumnName("absolute_expires_at");
                    b.Property<DateTimeOffset>("AuthenticatedAt").HasColumnType("timestamp with time zone").HasColumnName("authenticated_at");
                    b.Property<string>("AuthenticationStrength").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("authentication_strength");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<Guid>("DeviceId").HasColumnType("uuid").HasColumnName("device_id");
                    b.Property<int>("IdleTimeoutSeconds").HasColumnType("integer").HasColumnName("idle_timeout_seconds");
                    b.Property<DateTimeOffset>("LastSeenAt").HasColumnType("timestamp with time zone").HasColumnName("last_seen_at");
                    b.Property<Guid>("PrincipalId").HasColumnType("uuid").HasColumnName("principal_id");
                    b.Property<string>("PrincipalType").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("principal_type");
                    b.Property<bool>("Restricted").HasColumnType("boolean").HasColumnName("restricted");
                    b.Property<DateTimeOffset?>("RestrictedAt").HasColumnType("timestamp with time zone").HasColumnName("restricted_at");
                    b.Property<string>("RestrictionReason").HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("restriction_reason");
                    b.Property<DateTimeOffset?>("RevokedAt").HasColumnType("timestamp with time zone").HasColumnName("revoked_at");
                    b.Property<string>("RevocationReason").HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("revocation_reason");
                    b.HasKey("Id").HasName("pk_security_session");
                    b.HasIndex("AbsoluteExpiresAt").HasDatabaseName("ix_security_session_absolute_expires_at");
                    b.HasIndex("DeviceId", "PrincipalId", "PrincipalType");
                    b.HasIndex("DeviceId", "RevokedAt").HasDatabaseName("ix_security_session_device_lifecycle");
                    b.HasIndex("PrincipalId", "RevokedAt", "AbsoluteExpiresAt").HasDatabaseName("ix_security_session_principal_lifecycle");
                    b.ToTable("security_session", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_security_session_absolute_expiry", "absolute_expires_at > created_at");
                            t.HasCheckConstraint("ck_security_session_auth_chronology", "authenticated_at <= created_at");
                            t.HasCheckConstraint("ck_security_session_auth_strength", "authentication_strength IN ('password', 'strong_mfa', 'phishing_resistant')");
                            t.HasCheckConstraint("ck_security_session_idle_timeout", "idle_timeout_seconds > 0");
                            t.HasCheckConstraint("ck_security_session_last_seen_chronology", "last_seen_at >= created_at AND last_seen_at < absolute_expires_at");
                            t.HasCheckConstraint("ck_security_session_principal_type", "principal_type IN ('customer', 'staff', 'service')");
                            t.HasCheckConstraint("ck_security_session_restriction_chronology", "restricted_at IS NULL OR restricted_at >= created_at");
                            t.HasCheckConstraint("ck_security_session_restriction_pair", "(restricted_at IS NULL AND restriction_reason IS NULL) OR (restricted_at IS NOT NULL AND restriction_reason IS NOT NULL)");
                            t.HasCheckConstraint("ck_security_session_revocation_chronology", "revoked_at IS NULL OR revoked_at >= created_at");
                            t.HasCheckConstraint("ck_security_session_revocation_pair", "(revoked_at IS NULL AND revocation_reason IS NULL) OR (revoked_at IS NOT NULL AND revocation_reason IS NOT NULL)");
                            t.HasCheckConstraint("ck_security_session_state_evidence", "(revoked_at IS NULL AND restricted = FALSE AND restricted_at IS NULL) OR (revoked_at IS NULL AND restricted = TRUE AND restricted_at IS NOT NULL) OR (revoked_at IS NOT NULL AND restricted = FALSE)");
                            t.HasCheckConstraint("ck_security_session_transition_chronology", "restricted_at IS NULL OR revoked_at IS NULL OR revoked_at >= restricted_at");
                        });
                });

            modelBuilder.Entity("Klyvesta.Infrastructure.Persistence.Records.SecuritySessionRecord", b =>
                {
                    b.HasOne("Klyvesta.Infrastructure.Persistence.Records.SecurityDeviceRecord", null)
                        .WithMany()
                        .HasForeignKey("DeviceId", "PrincipalId", "PrincipalType")
                        .HasPrincipalKey("Id", "PrincipalId", "PrincipalType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_security_session_device_identity");
                });
#pragma warning restore 612, 618
        }
    }
}
