// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Klyvesta.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class F5SecuritySessionPersistence : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "identity");

            migrationBuilder.CreateTable(
                name: "security_device",
                schema: "identity",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    principal_id = table.Column<Guid>(type: "uuid", nullable: false),
                    principal_type = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    trust_state = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    integrity_state = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    registered_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    last_seen_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    restricted_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    restriction_reason = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: true),
                    revoked_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    revocation_reason = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_security_device", x => x.id);
                    table.UniqueConstraint(
                        "ak_security_device_identity",
                        x => new { x.id, x.principal_id, x.principal_type });
                    table.CheckConstraint(
                        "ck_security_device_integrity_state",
                        "integrity_state IN ('unknown', 'meets_baseline', 'degraded', 'failed')");
                    table.CheckConstraint(
                        "ck_security_device_last_seen_chronology",
                        "last_seen_at >= registered_at");
                    table.CheckConstraint(
                        "ck_security_device_principal_type",
                        "principal_type IN ('customer', 'staff', 'service')");
                    table.CheckConstraint(
                        "ck_security_device_restriction_chronology",
                        "restricted_at IS NULL OR restricted_at >= registered_at");
                    table.CheckConstraint(
                        "ck_security_device_restriction_pair",
                        "(restricted_at IS NULL AND restriction_reason IS NULL) OR (restricted_at IS NOT NULL AND restriction_reason IS NOT NULL)");
                    table.CheckConstraint(
                        "ck_security_device_revocation_chronology",
                        "revoked_at IS NULL OR revoked_at >= registered_at");
                    table.CheckConstraint(
                        "ck_security_device_revocation_pair",
                        "(revoked_at IS NULL AND revocation_reason IS NULL) OR (revoked_at IS NOT NULL AND revocation_reason IS NOT NULL)");
                    table.CheckConstraint(
                        "ck_security_device_state_evidence",
                        "(trust_state IN ('untrusted', 'trusted') AND restricted_at IS NULL AND revoked_at IS NULL) OR (trust_state = 'restricted' AND restricted_at IS NOT NULL AND revoked_at IS NULL) OR (trust_state = 'revoked' AND revoked_at IS NOT NULL)");
                    table.CheckConstraint(
                        "ck_security_device_transition_chronology",
                        "restricted_at IS NULL OR revoked_at IS NULL OR revoked_at >= restricted_at");
                    table.CheckConstraint(
                        "ck_security_device_trust_state",
                        "trust_state IN ('untrusted', 'trusted', 'restricted', 'revoked')");
                });

            migrationBuilder.CreateTable(
                name: "security_session",
                schema: "identity",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    principal_id = table.Column<Guid>(type: "uuid", nullable: false),
                    principal_type = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    device_id = table.Column<Guid>(type: "uuid", nullable: false),
                    authenticated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    last_seen_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    idle_timeout_seconds = table.Column<int>(type: "integer", nullable: false),
                    absolute_expires_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    authentication_strength = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    restricted = table.Column<bool>(type: "boolean", nullable: false),
                    restricted_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    restriction_reason = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: true),
                    revoked_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    revocation_reason = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_security_session", x => x.id);
                    table.CheckConstraint(
                        "ck_security_session_absolute_expiry",
                        "absolute_expires_at > created_at");
                    table.CheckConstraint(
                        "ck_security_session_auth_chronology",
                        "authenticated_at <= created_at");
                    table.CheckConstraint(
                        "ck_security_session_auth_strength",
                        "authentication_strength IN ('password', 'strong_mfa', 'phishing_resistant')");
                    table.CheckConstraint(
                        "ck_security_session_idle_timeout",
                        "idle_timeout_seconds > 0");
                    table.CheckConstraint(
                        "ck_security_session_last_seen_chronology",
                        "last_seen_at >= created_at AND last_seen_at < absolute_expires_at");
                    table.CheckConstraint(
                        "ck_security_session_principal_type",
                        "principal_type IN ('customer', 'staff', 'service')");
                    table.CheckConstraint(
                        "ck_security_session_restriction_chronology",
                        "restricted_at IS NULL OR restricted_at >= created_at");
                    table.CheckConstraint(
                        "ck_security_session_restriction_pair",
                        "(restricted_at IS NULL AND restriction_reason IS NULL) OR (restricted_at IS NOT NULL AND restriction_reason IS NOT NULL)");
                    table.CheckConstraint(
                        "ck_security_session_revocation_chronology",
                        "revoked_at IS NULL OR revoked_at >= created_at");
                    table.CheckConstraint(
                        "ck_security_session_revocation_pair",
                        "(revoked_at IS NULL AND revocation_reason IS NULL) OR (revoked_at IS NOT NULL AND revocation_reason IS NOT NULL)");
                    table.CheckConstraint(
                        "ck_security_session_state_evidence",
                        "(revoked_at IS NULL AND restricted = FALSE AND restricted_at IS NULL) OR (revoked_at IS NULL AND restricted = TRUE AND restricted_at IS NOT NULL) OR (revoked_at IS NOT NULL AND restricted = FALSE)");
                    table.CheckConstraint(
                        "ck_security_session_transition_chronology",
                        "restricted_at IS NULL OR revoked_at IS NULL OR revoked_at >= restricted_at");
                    table.ForeignKey(
                        name: "fk_security_session_device_identity",
                        columns: x => new { x.device_id, x.principal_id, x.principal_type },
                        principalSchema: "identity",
                        principalTable: "security_device",
                        principalColumns: new[] { "id", "principal_id", "principal_type" },
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "ix_security_device_last_seen_at",
                schema: "identity",
                table: "security_device",
                column: "last_seen_at");

            migrationBuilder.CreateIndex(
                name: "ix_security_device_principal_state",
                schema: "identity",
                table: "security_device",
                columns: new[] { "principal_id", "trust_state" });

            migrationBuilder.CreateIndex(
                name: "ix_security_session_absolute_expires_at",
                schema: "identity",
                table: "security_session",
                column: "absolute_expires_at");

            migrationBuilder.CreateIndex(
                name: "ix_security_session_device_lifecycle",
                schema: "identity",
                table: "security_session",
                columns: new[] { "device_id", "revoked_at" });

            migrationBuilder.CreateIndex(
                name: "ix_security_session_principal_lifecycle",
                schema: "identity",
                table: "security_session",
                columns: new[] { "principal_id", "revoked_at", "absolute_expires_at" });

            migrationBuilder.CreateIndex(
                name: "IX_security_session_device_id_principal_id_principal_type",
                schema: "identity",
                table: "security_session",
                columns: new[] { "device_id", "principal_id", "principal_type" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "security_session",
                schema: "identity");

            migrationBuilder.DropTable(
                name: "security_device",
                schema: "identity");
        }
    }
}
