// <auto-generated />
using Klyvesta.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Klyvesta.Infrastructure.Persistence.Migrations;

[DbContext(typeof(KlyvestaDbContext))]
[Migration("20260825205500_F6WithdrawalSecurityHardening")]
public partial class F6WithdrawalSecurityHardening : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE OR REPLACE FUNCTION funding.enforce_withdrawal_beneficiary_lifecycle()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            BEGIN
                IF TG_OP = 'DELETE' THEN
                    RAISE EXCEPTION 'Withdrawal beneficiary versions are historical records and cannot be deleted'
                        USING ERRCODE = '23514';
                END IF;

                IF TG_OP = 'INSERT' THEN
                    IF NEW.state <> 'pending_verification' OR
                       NEW.verification_evidence_reference IS NOT NULL OR
                       NEW.verified_at IS NOT NULL OR
                       NEW.available_after IS NOT NULL OR
                       NEW.blocked_at IS NOT NULL OR
                       NEW.block_reason IS NOT NULL OR
                       NEW.revoked_at IS NOT NULL OR
                       NEW.revocation_reason IS NOT NULL THEN
                        RAISE EXCEPTION 'Beneficiary versions must start pending verification without lifecycle evidence'
                            USING ERRCODE = '23514';
                    END IF;

                    RETURN NEW;
                END IF;

                IF ROW(
                    NEW.version_id,
                    NEW.beneficiary_id,
                    NEW.version_number,
                    NEW.customer_id,
                    NEW.destination_hash,
                    NEW.created_at
                ) IS DISTINCT FROM ROW(
                    OLD.version_id,
                    OLD.beneficiary_id,
                    OLD.version_number,
                    OLD.customer_id,
                    OLD.destination_hash,
                    OLD.created_at
                ) THEN
                    RAISE EXCEPTION 'Beneficiary identity and destination data are immutable; create a new version instead'
                        USING ERRCODE = '23514';
                END IF;

                IF NEW.state = OLD.state THEN
                    RAISE EXCEPTION 'Beneficiary lifecycle updates must perform an explicit state transition'
                        USING ERRCODE = '23514';
                END IF;

                IF NOT (
                    (OLD.state = 'pending_verification' AND NEW.state IN ('verified_cooling_off', 'blocked', 'revoked')) OR
                    (OLD.state = 'verified_cooling_off' AND NEW.state IN ('active', 'blocked', 'revoked')) OR
                    (OLD.state = 'active' AND NEW.state IN ('blocked', 'revoked')) OR
                    (OLD.state = 'blocked' AND NEW.state = 'revoked')
                ) THEN
                    RAISE EXCEPTION 'Invalid beneficiary lifecycle transition: % -> %', OLD.state, NEW.state
                        USING ERRCODE = '23514';
                END IF;

                IF OLD.state = 'pending_verification' AND NEW.state = 'verified_cooling_off' THEN
                    IF NEW.verification_evidence_reference IS NULL OR
                       btrim(NEW.verification_evidence_reference) = '' OR
                       NEW.verified_at IS NULL OR
                       NEW.available_after IS NULL OR
                       NEW.verified_at < NEW.created_at OR
                       NEW.available_after < NEW.verified_at THEN
                        RAISE EXCEPTION 'Beneficiary verification requires durable evidence and valid chronology'
                            USING ERRCODE = '23514';
                    END IF;
                ELSIF ROW(
                    NEW.verification_evidence_reference,
                    NEW.verified_at,
                    NEW.available_after
                ) IS DISTINCT FROM ROW(
                    OLD.verification_evidence_reference,
                    OLD.verified_at,
                    OLD.available_after
                ) THEN
                    RAISE EXCEPTION 'Beneficiary verification evidence is immutable once recorded'
                        USING ERRCODE = '23514';
                END IF;

                IF NEW.state = 'blocked' THEN
                    IF NEW.blocked_at IS NULL OR NEW.block_reason IS NULL OR btrim(NEW.block_reason) = '' THEN
                        RAISE EXCEPTION 'Blocked beneficiary requires reason-coded evidence'
                            USING ERRCODE = '23514';
                    END IF;
                ELSIF ROW(NEW.blocked_at, NEW.block_reason) IS DISTINCT FROM ROW(OLD.blocked_at, OLD.block_reason) THEN
                    RAISE EXCEPTION 'Beneficiary block evidence may only be created when entering blocked state'
                        USING ERRCODE = '23514';
                END IF;

                IF NEW.state = 'revoked' THEN
                    IF NEW.revoked_at IS NULL OR NEW.revocation_reason IS NULL OR btrim(NEW.revocation_reason) = '' THEN
                        RAISE EXCEPTION 'Revoked beneficiary requires reason-coded evidence'
                            USING ERRCODE = '23514';
                    END IF;
                ELSIF ROW(NEW.revoked_at, NEW.revocation_reason) IS DISTINCT FROM ROW(OLD.revoked_at, OLD.revocation_reason) THEN
                    RAISE EXCEPTION 'Beneficiary revocation evidence may only be created when entering revoked state'
                        USING ERRCODE = '23514';
                END IF;

                IF NEW.state = 'active' AND
                   (NEW.available_after IS NULL OR clock_timestamp() < NEW.available_after) THEN
                    RAISE EXCEPTION 'Beneficiary cannot become active before cooling-off completes'
                        USING ERRCODE = '23514';
                END IF;

                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER trg_withdrawal_beneficiary_lifecycle
            BEFORE INSERT OR UPDATE OR DELETE
            ON funding.withdrawal_beneficiary_version
            FOR EACH ROW
            EXECUTE FUNCTION funding.enforce_withdrawal_beneficiary_lifecycle();

            CREATE OR REPLACE FUNCTION funding.enforce_withdrawal_authorization_lifecycle()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            DECLARE
                withdrawal_state text;
                session_record identity.security_session%ROWTYPE;
                device_trust_state text;
                evaluated_at timestamp with time zone := clock_timestamp();
            BEGIN
                IF TG_OP IN ('UPDATE', 'DELETE') THEN
                    RAISE EXCEPTION 'Withdrawal authorization snapshots are append-only'
                        USING ERRCODE = '23514';
                END IF;

                SELECT w.state
                  INTO withdrawal_state
                  FROM funding.withdrawal w
                 WHERE w.id = NEW.withdrawal_id
                   AND w.requested_by_principal_id = NEW.principal_id
                   AND w.transaction_data_hash = NEW.transaction_data_hash;

                IF NOT FOUND OR withdrawal_state <> 'approved' THEN
                    RAISE EXCEPTION 'Withdrawal authorization must bind the exact approved request and requester'
                        USING ERRCODE = '23514';
                END IF;

                SELECT s.*
                  INTO session_record
                  FROM identity.security_session s
                 WHERE s.id = NEW.session_id
                   AND s.principal_id = NEW.principal_id;

                IF NOT FOUND OR
                   session_record.principal_type <> 'customer' OR
                   session_record.restricted OR
                   session_record.revoked_at IS NOT NULL OR
                   evaluated_at >= session_record.absolute_expires_at OR
                   evaluated_at >= session_record.last_seen_at + (session_record.idle_timeout_seconds * interval '1 second') THEN
                    RAISE EXCEPTION 'Withdrawal authorization requires a currently active customer session'
                        USING ERRCODE = '23514';
                END IF;

                SELECT d.trust_state
                  INTO device_trust_state
                  FROM identity.security_device d
                 WHERE d.id = session_record.device_id
                   AND d.principal_id = session_record.principal_id
                   AND d.principal_type = session_record.principal_type;

                IF NOT FOUND OR device_trust_state IN ('restricted', 'revoked') THEN
                    RAISE EXCEPTION 'Withdrawal authorization cannot use a restricted or revoked device'
                        USING ERRCODE = '23514';
                END IF;

                IF NEW.authorized_at > evaluated_at OR
                   NEW.authorized_at < session_record.created_at OR
                   NEW.authorized_at >= session_record.absolute_expires_at OR
                   NEW.expires_at <= evaluated_at OR
                   NEW.expires_at > session_record.absolute_expires_at THEN
                    RAISE EXCEPTION 'Withdrawal authorization timestamp is outside the active session lifetime'
                        USING ERRCODE = '23514';
                END IF;

                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER trg_withdrawal_authorization_lifecycle
            BEFORE INSERT OR UPDATE OR DELETE
            ON funding.withdrawal_authorization
            FOR EACH ROW
            EXECUTE FUNCTION funding.enforce_withdrawal_authorization_lifecycle();

            CREATE OR REPLACE FUNCTION funding.enforce_withdrawal_lifecycle()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            DECLARE
                beneficiary_state text;
                beneficiary_available_after timestamp with time zone;
                authorization_record funding.withdrawal_authorization%ROWTYPE;
                session_record identity.security_session%ROWTYPE;
                device_trust_state text;
                evaluated_at timestamp with time zone := clock_timestamp();
            BEGIN
                IF TG_OP = 'DELETE' THEN
                    RAISE EXCEPTION 'Withdrawal records are historical and cannot be deleted'
                        USING ERRCODE = '23514';
                END IF;

                IF TG_OP = 'INSERT' THEN
                    IF NEW.state <> 'requested' OR
                       NEW.updated_at IS DISTINCT FROM NEW.created_at OR
                       NEW.reason_code IS NOT NULL OR
                       NEW.approved_by_principal_id IS NOT NULL OR
                       NEW.approved_at IS NOT NULL OR
                       NEW.authorization_id IS NOT NULL OR
                       NEW.external_reference IS NOT NULL OR
                       NEW.outcome_evidence_reference IS NOT NULL THEN
                        RAISE EXCEPTION 'Withdrawals must start in clean requested state'
                            USING ERRCODE = '23514';
                    END IF;

                    SELECT b.state, b.available_after
                      INTO beneficiary_state, beneficiary_available_after
                      FROM funding.withdrawal_beneficiary_version b
                     WHERE b.version_id = NEW.beneficiary_version_id
                       AND b.customer_id = NEW.customer_id
                       AND b.destination_hash = NEW.destination_hash;

                    IF NOT FOUND OR
                       beneficiary_state <> 'active' OR
                       beneficiary_available_after IS NULL OR
                       NEW.created_at < beneficiary_available_after THEN
                        RAISE EXCEPTION 'Withdrawal requires the exact active beneficiary version outside cooling-off'
                            USING ERRCODE = '23514';
                    END IF;

                    RETURN NEW;
                END IF;

                IF ROW(
                    NEW.id,
                    NEW.customer_id,
                    NEW.beneficiary_version_id,
                    NEW.amount,
                    NEW.currency,
                    NEW.destination_hash,
                    NEW.transaction_data_hash,
                    NEW.requested_by_principal_id,
                    NEW.created_at
                ) IS DISTINCT FROM ROW(
                    OLD.id,
                    OLD.customer_id,
                    OLD.beneficiary_version_id,
                    OLD.amount,
                    OLD.currency,
                    OLD.destination_hash,
                    OLD.transaction_data_hash,
                    OLD.requested_by_principal_id,
                    OLD.created_at
                ) THEN
                    RAISE EXCEPTION 'Significant withdrawal transaction data is immutable; create a new request instead'
                        USING ERRCODE = '23514';
                END IF;

                IF NEW.updated_at < OLD.updated_at OR NEW.state = OLD.state THEN
                    RAISE EXCEPTION 'Withdrawal updates require monotonic chronology and an explicit state transition'
                        USING ERRCODE = '23514';
                END IF;

                IF NOT (
                    (OLD.state = 'requested' AND NEW.state = 'security_check') OR
                    (OLD.state = 'security_check' AND NEW.state IN ('security_hold', 'policy_check')) OR
                    (OLD.state = 'security_hold' AND NEW.state = 'security_check') OR
                    (OLD.state = 'policy_check' AND NEW.state IN ('rejected', 'approval_pending', 'approved')) OR
                    (OLD.state = 'approval_pending' AND NEW.state = 'approved') OR
                    (OLD.state = 'approved' AND NEW.state = 'submission_pending') OR
                    (OLD.state = 'submission_pending' AND NEW.state IN ('submitted', 'unknown')) OR
                    (OLD.state = 'submitted' AND NEW.state IN ('processing', 'failed', 'unknown')) OR
                    (OLD.state = 'processing' AND NEW.state IN ('completed', 'failed', 'unknown')) OR
                    (OLD.state = 'unknown' AND NEW.state IN ('completed', 'failed'))
                ) THEN
                    RAISE EXCEPTION 'Invalid withdrawal lifecycle transition: % -> %', OLD.state, NEW.state
                        USING ERRCODE = '23514';
                END IF;

                IF OLD.state = 'approval_pending' AND NEW.state = 'approved' THEN
                    IF NEW.approved_by_principal_id IS NULL OR
                       NEW.approved_at IS NULL OR
                       NEW.approved_by_principal_id = NEW.requested_by_principal_id OR
                       NEW.approved_at < OLD.updated_at OR
                       NEW.approved_at > NEW.updated_at THEN
                        RAISE EXCEPTION 'Protected withdrawal approval requires distinct maker-checker evidence'
                            USING ERRCODE = '23514';
                    END IF;
                ELSIF OLD.state = 'policy_check' AND NEW.state = 'approved' THEN
                    IF NEW.approved_by_principal_id IS NOT NULL OR NEW.approved_at IS NOT NULL THEN
                        RAISE EXCEPTION 'Direct policy approval cannot fabricate maker-checker evidence'
                            USING ERRCODE = '23514';
                    END IF;
                ELSIF ROW(NEW.approved_by_principal_id, NEW.approved_at)
                    IS DISTINCT FROM ROW(OLD.approved_by_principal_id, OLD.approved_at) THEN
                    RAISE EXCEPTION 'Withdrawal approval evidence may only be created by the protected approval transition'
                        USING ERRCODE = '23514';
                END IF;

                IF NEW.state IN ('security_hold', 'rejected', 'failed', 'unknown') THEN
                    IF NEW.reason_code IS NULL OR btrim(NEW.reason_code) = '' THEN
                        RAISE EXCEPTION 'Reason-coded withdrawal state requires a non-blank reason'
                            USING ERRCODE = '23514';
                    END IF;
                ELSIF NEW.reason_code IS DISTINCT FROM OLD.reason_code THEN
                    RAISE EXCEPTION 'Withdrawal reason may only change when entering a reason-coded state'
                        USING ERRCODE = '23514';
                END IF;

                IF OLD.state = 'approved' AND NEW.state = 'submission_pending' THEN
                    IF NEW.authorization_id IS NULL THEN
                        RAISE EXCEPTION 'Submission preparation requires an authorization snapshot'
                            USING ERRCODE = '23514';
                    END IF;

                    SELECT a.*
                      INTO authorization_record
                      FROM funding.withdrawal_authorization a
                     WHERE a.id = NEW.authorization_id
                       AND a.withdrawal_id = NEW.id
                       AND a.principal_id = NEW.requested_by_principal_id
                       AND a.transaction_data_hash = NEW.transaction_data_hash;

                    IF NOT FOUND OR
                       evaluated_at < authorization_record.authorized_at OR
                       evaluated_at >= authorization_record.expires_at THEN
                        RAISE EXCEPTION 'Selected withdrawal authorization is missing, mismatched, or expired'
                            USING ERRCODE = '23514';
                    END IF;

                    SELECT s.*
                      INTO session_record
                      FROM identity.security_session s
                     WHERE s.id = authorization_record.session_id
                       AND s.principal_id = authorization_record.principal_id;

                    IF NOT FOUND OR
                       session_record.principal_type <> 'customer' OR
                       session_record.restricted OR
                       session_record.revoked_at IS NOT NULL OR
                       evaluated_at >= session_record.absolute_expires_at OR
                       evaluated_at >= session_record.last_seen_at + (session_record.idle_timeout_seconds * interval '1 second') THEN
                        RAISE EXCEPTION 'Withdrawal session is no longer active at submission preparation'
                            USING ERRCODE = '23514';
                    END IF;

                    SELECT d.trust_state
                      INTO device_trust_state
                      FROM identity.security_device d
                     WHERE d.id = session_record.device_id
                       AND d.principal_id = session_record.principal_id
                       AND d.principal_type = session_record.principal_type;

                    IF NOT FOUND OR device_trust_state IN ('restricted', 'revoked') THEN
                        RAISE EXCEPTION 'Withdrawal device is no longer eligible at submission preparation'
                            USING ERRCODE = '23514';
                    END IF;

                    SELECT b.state, b.available_after
                      INTO beneficiary_state, beneficiary_available_after
                      FROM funding.withdrawal_beneficiary_version b
                     WHERE b.version_id = NEW.beneficiary_version_id
                       AND b.customer_id = NEW.customer_id
                       AND b.destination_hash = NEW.destination_hash;

                    IF NOT FOUND OR
                       beneficiary_state <> 'active' OR
                       beneficiary_available_after IS NULL OR
                       evaluated_at < beneficiary_available_after THEN
                        RAISE EXCEPTION 'Withdrawal beneficiary is no longer eligible at submission preparation'
                            USING ERRCODE = '23514';
                    END IF;
                ELSIF NEW.authorization_id IS DISTINCT FROM OLD.authorization_id THEN
                    RAISE EXCEPTION 'Selected authorization may only be set during approved to submission-pending transition'
                        USING ERRCODE = '23514';
                END IF;

                IF OLD.state = 'submission_pending' AND NEW.state = 'submitted' THEN
                    IF NEW.external_reference IS NULL OR btrim(NEW.external_reference) = '' THEN
                        RAISE EXCEPTION 'Submitted withdrawal requires an external reference'
                            USING ERRCODE = '23514';
                    END IF;
                ELSIF NEW.external_reference IS DISTINCT FROM OLD.external_reference THEN
                    RAISE EXCEPTION 'External reference may only be created when submission becomes conclusive'
                        USING ERRCODE = '23514';
                END IF;

                IF NEW.state IN ('completed', 'failed') THEN
                    IF NEW.outcome_evidence_reference IS NULL OR btrim(NEW.outcome_evidence_reference) = '' THEN
                        RAISE EXCEPTION 'Terminal withdrawal outcome requires reconciliation evidence'
                            USING ERRCODE = '23514';
                    END IF;
                ELSIF NEW.outcome_evidence_reference IS DISTINCT FROM OLD.outcome_evidence_reference THEN
                    RAISE EXCEPTION 'Outcome evidence may only be created on a terminal withdrawal transition'
                        USING ERRCODE = '23514';
                END IF;

                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER trg_withdrawal_lifecycle
            BEFORE INSERT OR UPDATE OR DELETE
            ON funding.withdrawal
            FOR EACH ROW
            EXECUTE FUNCTION funding.enforce_withdrawal_lifecycle();
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            DROP TRIGGER IF EXISTS trg_withdrawal_lifecycle ON funding.withdrawal;
            DROP FUNCTION IF EXISTS funding.enforce_withdrawal_lifecycle();

            DROP TRIGGER IF EXISTS trg_withdrawal_authorization_lifecycle ON funding.withdrawal_authorization;
            DROP FUNCTION IF EXISTS funding.enforce_withdrawal_authorization_lifecycle();

            DROP TRIGGER IF EXISTS trg_withdrawal_beneficiary_lifecycle ON funding.withdrawal_beneficiary_version;
            DROP FUNCTION IF EXISTS funding.enforce_withdrawal_beneficiary_lifecycle();
            """);
    }
}
