// <auto-generated />
using Klyvesta.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Klyvesta.Infrastructure.Persistence.Migrations;

[DbContext(typeof(KlyvestaDbContext))]
[Migration("20260825204000_F6WithdrawalSecurityPersistence")]
public partial class F6WithdrawalSecurityPersistence : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE SCHEMA IF NOT EXISTS funding;

            ALTER TABLE identity.security_session
                ADD CONSTRAINT ak_security_session_principal UNIQUE (id, principal_id);

            CREATE TABLE funding.withdrawal_beneficiary_version (
                version_id uuid NOT NULL,
                beneficiary_id uuid NOT NULL,
                version_number integer NOT NULL,
                customer_id uuid NOT NULL,
                destination_hash character(64) NOT NULL,
                state character varying(32) NOT NULL,
                verification_evidence_reference character varying(256) NULL,
                created_at timestamp with time zone NOT NULL,
                verified_at timestamp with time zone NULL,
                available_after timestamp with time zone NULL,
                blocked_at timestamp with time zone NULL,
                block_reason character varying(128) NULL,
                revoked_at timestamp with time zone NULL,
                revocation_reason character varying(128) NULL,
                CONSTRAINT pk_withdrawal_beneficiary_version PRIMARY KEY (version_id),
                CONSTRAINT ak_withdrawal_beneficiary_binding UNIQUE (version_id, customer_id, destination_hash),
                CONSTRAINT ck_withdrawal_beneficiary_identifiers CHECK (
                    version_id <> '00000000-0000-0000-0000-000000000000'::uuid AND
                    beneficiary_id <> '00000000-0000-0000-0000-000000000000'::uuid AND
                    customer_id <> '00000000-0000-0000-0000-000000000000'::uuid),
                CONSTRAINT ck_withdrawal_beneficiary_version_number CHECK (version_number > 0),
                CONSTRAINT ck_withdrawal_beneficiary_destination_hash CHECK (destination_hash ~ '^[0-9A-F]{64}$'),
                CONSTRAINT ck_withdrawal_beneficiary_state CHECK (
                    state IN ('pending_verification', 'verified_cooling_off', 'active', 'blocked', 'revoked')),
                CONSTRAINT ck_withdrawal_beneficiary_verification_evidence CHECK (
                    (verification_evidence_reference IS NULL AND verified_at IS NULL AND available_after IS NULL) OR
                    (verification_evidence_reference IS NOT NULL AND btrim(verification_evidence_reference) <> '' AND
                     verified_at IS NOT NULL AND available_after IS NOT NULL)),
                CONSTRAINT ck_withdrawal_beneficiary_verification_chronology CHECK (
                    verified_at IS NULL OR (verified_at >= created_at AND available_after >= verified_at)),
                CONSTRAINT ck_withdrawal_beneficiary_block_pair CHECK (
                    (blocked_at IS NULL AND block_reason IS NULL) OR
                    (blocked_at IS NOT NULL AND block_reason IS NOT NULL AND btrim(block_reason) <> '')),
                CONSTRAINT ck_withdrawal_beneficiary_revocation_pair CHECK (
                    (revoked_at IS NULL AND revocation_reason IS NULL) OR
                    (revoked_at IS NOT NULL AND revocation_reason IS NOT NULL AND btrim(revocation_reason) <> '')),
                CONSTRAINT ck_withdrawal_beneficiary_transition_chronology CHECK (
                    (blocked_at IS NULL OR blocked_at >= created_at) AND
                    (revoked_at IS NULL OR revoked_at >= created_at) AND
                    (blocked_at IS NULL OR revoked_at IS NULL OR revoked_at >= blocked_at)),
                CONSTRAINT ck_withdrawal_beneficiary_state_evidence CHECK (
                    (state = 'pending_verification' AND verification_evidence_reference IS NULL AND blocked_at IS NULL AND revoked_at IS NULL) OR
                    (state IN ('verified_cooling_off', 'active') AND verification_evidence_reference IS NOT NULL AND blocked_at IS NULL AND revoked_at IS NULL) OR
                    (state = 'blocked' AND blocked_at IS NOT NULL AND revoked_at IS NULL) OR
                    (state = 'revoked' AND revoked_at IS NOT NULL))
            );

            CREATE UNIQUE INDEX ux_withdrawal_beneficiary_version
                ON funding.withdrawal_beneficiary_version (beneficiary_id, version_number);
            CREATE INDEX ix_withdrawal_beneficiary_customer_state
                ON funding.withdrawal_beneficiary_version (customer_id, state);

            CREATE TABLE funding.withdrawal (
                id uuid NOT NULL,
                customer_id uuid NOT NULL,
                beneficiary_version_id uuid NOT NULL,
                amount numeric(24,8) NOT NULL,
                currency character(3) NOT NULL,
                destination_hash character(64) NOT NULL,
                transaction_data_hash character(64) NOT NULL,
                state character varying(32) NOT NULL,
                requested_by_principal_id uuid NOT NULL,
                created_at timestamp with time zone NOT NULL,
                updated_at timestamp with time zone NOT NULL,
                reason_code character varying(128) NULL,
                approved_by_principal_id uuid NULL,
                approved_at timestamp with time zone NULL,
                authorization_id uuid NULL,
                external_reference character varying(256) NULL,
                outcome_evidence_reference character varying(256) NULL,
                CONSTRAINT pk_withdrawal PRIMARY KEY (id),
                CONSTRAINT ak_withdrawal_request_authorization_binding UNIQUE (
                    id, requested_by_principal_id, transaction_data_hash),
                CONSTRAINT fk_withdrawal_beneficiary_binding FOREIGN KEY (
                    beneficiary_version_id, customer_id, destination_hash)
                    REFERENCES funding.withdrawal_beneficiary_version (
                        version_id, customer_id, destination_hash) ON DELETE RESTRICT,
                CONSTRAINT ck_withdrawal_identifiers CHECK (
                    id <> '00000000-0000-0000-0000-000000000000'::uuid AND
                    customer_id <> '00000000-0000-0000-0000-000000000000'::uuid AND
                    beneficiary_version_id <> '00000000-0000-0000-0000-000000000000'::uuid AND
                    requested_by_principal_id <> '00000000-0000-0000-0000-000000000000'::uuid AND
                    (approved_by_principal_id IS NULL OR approved_by_principal_id <> '00000000-0000-0000-0000-000000000000'::uuid) AND
                    (authorization_id IS NULL OR authorization_id <> '00000000-0000-0000-0000-000000000000'::uuid)),
                CONSTRAINT ck_withdrawal_amount CHECK (amount > 0),
                CONSTRAINT ck_withdrawal_currency CHECK (currency ~ '^[A-Z]{3}$'),
                CONSTRAINT ck_withdrawal_hashes CHECK (
                    destination_hash ~ '^[0-9A-F]{64}$' AND transaction_data_hash ~ '^[0-9A-F]{64}$'),
                CONSTRAINT ck_withdrawal_state CHECK (
                    state IN ('requested', 'security_check', 'security_hold', 'policy_check', 'rejected',
                              'approval_pending', 'approved', 'submission_pending', 'submitted', 'processing',
                              'completed', 'failed', 'unknown')),
                CONSTRAINT ck_withdrawal_chronology CHECK (updated_at >= created_at),
                CONSTRAINT ck_withdrawal_approval_pair CHECK (
                    (approved_by_principal_id IS NULL AND approved_at IS NULL) OR
                    (approved_by_principal_id IS NOT NULL AND approved_at IS NOT NULL AND
                     approved_at >= created_at AND approved_by_principal_id <> requested_by_principal_id)),
                CONSTRAINT ck_withdrawal_reason_content CHECK (reason_code IS NULL OR btrim(reason_code) <> ''),
                CONSTRAINT ck_withdrawal_reason_required CHECK (
                    state NOT IN ('security_hold', 'rejected', 'failed', 'unknown') OR reason_code IS NOT NULL),
                CONSTRAINT ck_withdrawal_authorization_state CHECK (
                    (state IN ('requested', 'security_check', 'security_hold', 'policy_check', 'rejected', 'approval_pending', 'approved') AND authorization_id IS NULL) OR
                    (state IN ('submission_pending', 'submitted', 'processing', 'completed', 'failed', 'unknown') AND authorization_id IS NOT NULL)),
                CONSTRAINT ck_withdrawal_external_reference CHECK (
                    (external_reference IS NULL OR btrim(external_reference) <> '') AND
                    (state NOT IN ('submitted', 'processing') OR external_reference IS NOT NULL)),
                CONSTRAINT ck_withdrawal_outcome_evidence CHECK (
                    (state IN ('completed', 'failed') AND outcome_evidence_reference IS NOT NULL AND btrim(outcome_evidence_reference) <> '') OR
                    (state NOT IN ('completed', 'failed') AND outcome_evidence_reference IS NULL))
            );

            CREATE INDEX ix_withdrawal_customer_state_created_at
                ON funding.withdrawal (customer_id, state, created_at);
            CREATE INDEX ix_withdrawal_beneficiary_binding
                ON funding.withdrawal (beneficiary_version_id, customer_id, destination_hash);
            CREATE INDEX ix_withdrawal_selected_authorization
                ON funding.withdrawal (authorization_id, id) WHERE authorization_id IS NOT NULL;

            CREATE TABLE funding.withdrawal_authorization (
                id uuid NOT NULL,
                withdrawal_id uuid NOT NULL,
                principal_id uuid NOT NULL,
                session_id uuid NOT NULL,
                transaction_data_hash character(64) NOT NULL,
                authorized_at timestamp with time zone NOT NULL,
                expires_at timestamp with time zone NOT NULL,
                CONSTRAINT pk_withdrawal_authorization PRIMARY KEY (id),
                CONSTRAINT ak_withdrawal_authorization_withdrawal UNIQUE (id, withdrawal_id),
                CONSTRAINT fk_withdrawal_authorization_request_binding FOREIGN KEY (
                    withdrawal_id, principal_id, transaction_data_hash)
                    REFERENCES funding.withdrawal (
                        id, requested_by_principal_id, transaction_data_hash) ON DELETE RESTRICT,
                CONSTRAINT fk_withdrawal_authorization_session_principal FOREIGN KEY (
                    session_id, principal_id)
                    REFERENCES identity.security_session (id, principal_id) ON DELETE RESTRICT,
                CONSTRAINT ck_withdrawal_authorization_identifiers CHECK (
                    id <> '00000000-0000-0000-0000-000000000000'::uuid AND
                    withdrawal_id <> '00000000-0000-0000-0000-000000000000'::uuid AND
                    principal_id <> '00000000-0000-0000-0000-000000000000'::uuid AND
                    session_id <> '00000000-0000-0000-0000-000000000000'::uuid),
                CONSTRAINT ck_withdrawal_authorization_hash CHECK (transaction_data_hash ~ '^[0-9A-F]{64}$'),
                CONSTRAINT ck_withdrawal_authorization_expiry CHECK (expires_at > authorized_at)
            );

            CREATE INDEX ix_withdrawal_authorization_withdrawal_expiry
                ON funding.withdrawal_authorization (withdrawal_id, expires_at);
            CREATE INDEX ix_withdrawal_authorization_binding
                ON funding.withdrawal_authorization (withdrawal_id, principal_id, transaction_data_hash);
            CREATE INDEX ix_withdrawal_authorization_session_principal
                ON funding.withdrawal_authorization (session_id, principal_id);

            ALTER TABLE funding.withdrawal
                ADD CONSTRAINT fk_withdrawal_selected_authorization FOREIGN KEY (authorization_id, id)
                REFERENCES funding.withdrawal_authorization (id, withdrawal_id) ON DELETE RESTRICT;
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            ALTER TABLE funding.withdrawal
                DROP CONSTRAINT IF EXISTS fk_withdrawal_selected_authorization;

            DROP TABLE IF EXISTS funding.withdrawal_authorization;
            DROP TABLE IF EXISTS funding.withdrawal;
            DROP TABLE IF EXISTS funding.withdrawal_beneficiary_version;

            ALTER TABLE identity.security_session
                DROP CONSTRAINT IF EXISTS ak_security_session_principal;

            DROP SCHEMA IF EXISTS funding;
            """);
    }
}
