// <auto-generated />
using System;
using Klyvesta.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Klyvesta.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KlyvestaDbContext))]
    partial class KlyvestaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Klyvesta.Infrastructure.Persistence.Records.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<DateTimeOffset?>("CompletedAt").HasColumnType("timestamp with time zone").HasColumnName("completed_at");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<DateTimeOffset>("ExpiresAt").HasColumnType("timestamp with time zone").HasColumnName("expires_at");
                    b.Property<string>("Key").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("key");
                    b.Property<Guid?>("OperationId").HasColumnType("uuid").HasColumnName("operation_id");
                    b.Property<string>("RequestHash").IsRequired().HasColumnType("character(64)").HasColumnName("request_hash");
                    b.Property<string>("Scope").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("scope");
                    b.Property<string>("State").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("state");
                    b.HasKey("Id").HasName("pk_idempotency_record");
                    b.HasIndex("ExpiresAt").HasDatabaseName("ix_idempotency_record_expires_at");
                    b.HasIndex("Scope", "Key").IsUnique().HasDatabaseName("ux_idempotency_record_scope_key");
                    b.ToTable("idempotency_record", "ops", t =>
                        {
                            t.HasCheckConstraint("ck_idempotency_record_completion_chronology", "completed_at IS NULL OR completed_at >= created_at");
                            t.HasCheckConstraint("ck_idempotency_record_expiry", "expires_at > created_at");
                            t.HasCheckConstraint("ck_idempotency_record_state", "state IN ('in_progress', 'completed', 'failed')");
                        });
                });

            modelBuilder.Entity("Klyvesta.Infrastructure.Persistence.Records.InboxMessage", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<string>("MessageId").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("message_id");
                    b.Property<string>("PayloadHash").IsRequired().HasColumnType("character(64)").HasColumnName("payload_hash");
                    b.Property<string>("PayloadJson").IsRequired().HasColumnType("jsonb").HasColumnName("payload_json");
                    b.Property<DateTimeOffset?>("ProcessedAt").HasColumnType("timestamp with time zone").HasColumnName("processed_at");
                    b.Property<string>("Provider").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("provider");
                    b.Property<DateTimeOffset>("ReceivedAt").HasColumnType("timestamp with time zone").HasColumnName("received_at");
                    b.Property<string>("State").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("state");
                    b.HasKey("Id").HasName("pk_inbox_message");
                    b.HasIndex("Provider", "MessageId").IsUnique().HasDatabaseName("ux_inbox_message_provider_message_id");
                    b.HasIndex("State", "ReceivedAt").HasDatabaseName("ix_inbox_message_state_received_at");
                    b.ToTable("inbox_message", "ops", t =>
                        {
                            t.HasCheckConstraint("ck_inbox_message_processing_chronology", "processed_at IS NULL OR processed_at >= received_at");
                            t.HasCheckConstraint("ck_inbox_message_state", "state IN ('received', 'processing', 'processed', 'failed')");
                        });
                });

            modelBuilder.Entity("Klyvesta.Infrastructure.Persistence.Records.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<int>("AttemptCount").HasColumnType("integer").HasColumnName("attempt_count");
                    b.Property<string>("EventType").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("event_type");
                    b.Property<string>("HeadersJson").HasColumnType("jsonb").HasColumnName("headers_json");
                    b.Property<string>("LastErrorCode").HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("last_error_code");
                    b.Property<DateTimeOffset?>("NextAttemptAt").HasColumnType("timestamp with time zone").HasColumnName("next_attempt_at");
                    b.Property<DateTimeOffset>("OccurredAt").HasColumnType("timestamp with time zone").HasColumnName("occurred_at");
                    b.Property<string>("PayloadJson").IsRequired().HasColumnType("jsonb").HasColumnName("payload_json");
                    b.Property<DateTimeOffset?>("PublishedAt").HasColumnType("timestamp with time zone").HasColumnName("published_at");
                    b.HasKey("Id").HasName("pk_outbox");
                    b.HasIndex("NextAttemptAt", "OccurredAt").HasDatabaseName("ix_outbox_pending").HasFilter("published_at IS NULL");
                    b.ToTable("outbox", "notification", t =>
                        {
                            t.HasCheckConstraint("ck_outbox_attempt_count", "attempt_count >= 0");
                        });
                });

            modelBuilder.Entity("Klyvesta.Infrastructure.Persistence.Records.SecurityDeviceRecord", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<string>("IntegrityState").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("integrity_state");
                    b.Property<DateTimeOffset>("LastSeenAt").HasColumnType("timestamp with time zone").HasColumnName("last_seen_at");
                    b.Property<Guid>("PrincipalId").HasColumnType("uuid").HasColumnName("principal_id");
                    b.Property<string>("PrincipalType").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("principal_type");
                    b.Property<DateTimeOffset>("RegisteredAt").HasColumnType("timestamp with time zone").HasColumnName("registered_at");
                    b.Property<DateTimeOffset?>("RestrictedAt").HasColumnType("timestamp with time zone").HasColumnName("restricted_at");
                    b.Property<string>("RestrictionReason").HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("restriction_reason");
                    b.Property<DateTimeOffset?>("RevokedAt").HasColumnType("timestamp with time zone").HasColumnName("revoked_at");
                    b.Property<string>("RevocationReason").HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("revocation_reason");
                    b.Property<string>("TrustState").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("trust_state");
                    b.HasKey("Id").HasName("pk_security_device");
                    b.HasAlternateKey("Id", "PrincipalId", "PrincipalType").HasName("ak_security_device_identity");
                    b.HasIndex("LastSeenAt").HasDatabaseName("ix_security_device_last_seen_at");
                    b.HasIndex("PrincipalId", "TrustState").HasDatabaseName("ix_security_device_principal_state");
                    b.ToTable("security_device", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_security_device_identifiers", "id <> '00000000-0000-0000-0000-000000000000'::uuid AND principal_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                            t.HasCheckConstraint("ck_security_device_integrity_state", "integrity_state IN ('unknown', 'meets_baseline', 'degraded', 'failed')");
                            t.HasCheckConstraint("ck_security_device_last_seen_chronology", "last_seen_at >= registered_at");
                            t.HasCheckConstraint("ck_security_device_principal_type", "principal_type IN ('customer', 'staff', 'service')");
                            t.HasCheckConstraint("ck_security_device_reason_content", "(restriction_reason IS NULL OR btrim(restriction_reason) <> '') AND (revocation_reason IS NULL OR btrim(revocation_reason) <> '')");
                            t.HasCheckConstraint("ck_security_device_restriction_chronology", "restricted_at IS NULL OR restricted_at >= registered_at");
                            t.HasCheckConstraint("ck_security_device_restriction_pair", "(restricted_at IS NULL AND restriction_reason IS NULL) OR (restricted_at IS NOT NULL AND restriction_reason IS NOT NULL)");
                            t.HasCheckConstraint("ck_security_device_revocation_chronology", "revoked_at IS NULL OR revoked_at >= registered_at");
                            t.HasCheckConstraint("ck_security_device_revocation_pair", "(revoked_at IS NULL AND revocation_reason IS NULL) OR (revoked_at IS NOT NULL AND revocation_reason IS NOT NULL)");
                            t.HasCheckConstraint("ck_security_device_state_evidence", "(trust_state IN ('untrusted', 'trusted') AND restricted_at IS NULL AND revoked_at IS NULL) OR (trust_state = 'restricted' AND restricted_at IS NOT NULL AND revoked_at IS NULL) OR (trust_state = 'revoked' AND revoked_at IS NOT NULL)");
                            t.HasCheckConstraint("ck_security_device_transition_chronology", "restricted_at IS NULL OR revoked_at IS NULL OR revoked_at >= restricted_at");
                            t.HasCheckConstraint("ck_security_device_trust_state", "trust_state IN ('untrusted', 'trusted', 'restricted', 'revoked')");
                        });
                });

            modelBuilder.Entity("Klyvesta.Infrastructure.Persistence.Records.SecuritySessionRecord", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<DateTimeOffset>("AbsoluteExpiresAt").HasColumnType("timestamp with time zone").HasColumnName("absolute_expires_at");
                    b.Property<DateTimeOffset>("AuthenticatedAt").HasColumnType("timestamp with time zone").HasColumnName("authenticated_at");
                    b.Property<string>("AuthenticationStrength").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("authentication_strength");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<Guid>("DeviceId").HasColumnType("uuid").HasColumnName("device_id");
                    b.Property<int>("IdleTimeoutSeconds").HasColumnType("integer").HasColumnName("idle_timeout_seconds");
                    b.Property<DateTimeOffset>("LastSeenAt").HasColumnType("timestamp with time zone").HasColumnName("last_seen_at");
                    b.Property<Guid>("PrincipalId").HasColumnType("uuid").HasColumnName("principal_id");
                    b.Property<string>("PrincipalType").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("principal_type");
                    b.Property<bool>("Restricted").HasColumnType("boolean").HasColumnName("restricted");
                    b.Property<DateTimeOffset?>("RestrictedAt").HasColumnType("timestamp with time zone").HasColumnName("restricted_at");
                    b.Property<string>("RestrictionReason").HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("restriction_reason");
                    b.Property<DateTimeOffset?>("RevokedAt").HasColumnType("timestamp with time zone").HasColumnName("revoked_at");
                    b.Property<string>("RevocationReason").HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("revocation_reason");
                    b.HasKey("Id").HasName("pk_security_session");
                    b.HasAlternateKey("Id", "PrincipalId").HasName("ak_security_session_principal");
                    b.HasIndex("AbsoluteExpiresAt").HasDatabaseName("ix_security_session_absolute_expires_at");
                    b.HasIndex("DeviceId", "PrincipalId", "PrincipalType");
                    b.HasIndex("DeviceId", "RevokedAt").HasDatabaseName("ix_security_session_device_lifecycle");
                    b.HasIndex("PrincipalId", "RevokedAt", "AbsoluteExpiresAt").HasDatabaseName("ix_security_session_principal_lifecycle");
                    b.ToTable("security_session", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_security_session_absolute_expiry", "absolute_expires_at > created_at");
                            t.HasCheckConstraint("ck_security_session_auth_chronology", "authenticated_at <= created_at");
                            t.HasCheckConstraint("ck_security_session_auth_strength", "authentication_strength IN ('password', 'strong_mfa', 'phishing_resistant')");
                            t.HasCheckConstraint("ck_security_session_identifiers", "id <> '00000000-0000-0000-0000-000000000000'::uuid AND principal_id <> '00000000-0000-0000-0000-000000000000'::uuid AND device_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                            t.HasCheckConstraint("ck_security_session_idle_timeout", "idle_timeout_seconds > 0");
                            t.HasCheckConstraint("ck_security_session_last_seen_chronology", "last_seen_at >= created_at AND last_seen_at < absolute_expires_at");
                            t.HasCheckConstraint("ck_security_session_principal_type", "principal_type IN ('customer', 'staff', 'service')");
                            t.HasCheckConstraint("ck_security_session_reason_content", "(restriction_reason IS NULL OR btrim(restriction_reason) <> '') AND (revocation_reason IS NULL OR btrim(revocation_reason) <> '')");
                            t.HasCheckConstraint("ck_security_session_restriction_chronology", "restricted_at IS NULL OR restricted_at >= created_at");
                            t.HasCheckConstraint("ck_security_session_restriction_pair", "(restricted_at IS NULL AND restriction_reason IS NULL) OR (restricted_at IS NOT NULL AND restriction_reason IS NOT NULL)");
                            t.HasCheckConstraint("ck_security_session_revocation_chronology", "revoked_at IS NULL OR revoked_at >= created_at");
                            t.HasCheckConstraint("ck_security_session_revocation_pair", "(revoked_at IS NULL AND revocation_reason IS NULL) OR (revoked_at IS NOT NULL AND revocation_reason IS NOT NULL)");
                            t.HasCheckConstraint("ck_security_session_revocation_reason", "revocation_reason IS NULL OR revocation_reason IN ('user_sign_out', 'sign_out_all', 'device_revoked', 'recovery_completed', 'staff_privilege_changed', 'security_incident', 'credential_compromise', 'account_suspended')");
                            t.HasCheckConstraint("ck_security_session_state_evidence", "(revoked_at IS NULL AND restricted = FALSE AND restricted_at IS NULL) OR (revoked_at IS NULL AND restricted = TRUE AND restricted_at IS NOT NULL) OR (revoked_at IS NOT NULL AND restricted = FALSE)");
                            t.HasCheckConstraint("ck_security_session_transition_chronology", "restricted_at IS NULL OR revoked_at IS NULL OR revoked_at >= restricted_at");
                        });
                });

            modelBuilder.Entity("Klyvesta.Infrastructure.Persistence.Records.WithdrawalAuthorizationRecord", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<DateTimeOffset>("AuthorizedAt").HasColumnType("timestamp with time zone").HasColumnName("authorized_at");
                    b.Property<DateTimeOffset>("ExpiresAt").HasColumnType("timestamp with time zone").HasColumnName("expires_at");
                    b.Property<Guid>("PrincipalId").HasColumnType("uuid").HasColumnName("principal_id");
                    b.Property<Guid>("SessionId").HasColumnType("uuid").HasColumnName("session_id");
                    b.Property<string>("TransactionDataHash").IsRequired().HasColumnType("character(64)").HasColumnName("transaction_data_hash");
                    b.Property<Guid>("WithdrawalId").HasColumnType("uuid").HasColumnName("withdrawal_id");
                    b.HasKey("Id").HasName("pk_withdrawal_authorization");
                    b.HasAlternateKey("Id", "WithdrawalId").HasName("ak_withdrawal_authorization_withdrawal");
                    b.HasIndex("SessionId", "PrincipalId").HasDatabaseName("ix_withdrawal_authorization_session_principal");
                    b.HasIndex("WithdrawalId", "ExpiresAt").HasDatabaseName("ix_withdrawal_authorization_withdrawal_expiry");
                    b.HasIndex("WithdrawalId", "PrincipalId", "TransactionDataHash").HasDatabaseName("ix_withdrawal_authorization_binding");
                    b.ToTable("withdrawal_authorization", "funding", t =>
                        {
                            t.HasCheckConstraint("ck_withdrawal_authorization_expiry", "expires_at > authorized_at");
                            t.HasCheckConstraint("ck_withdrawal_authorization_hash", "transaction_data_hash ~ '^[0-9A-F]{64}$'");
                            t.HasCheckConstraint("ck_withdrawal_authorization_identifiers", "id <> '00000000-0000-0000-0000-000000000000'::uuid AND withdrawal_id <> '00000000-0000-0000-0000-000000000000'::uuid AND principal_id <> '00000000-0000-0000-0000-000000000000'::uuid AND session_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("Klyvesta.Infrastructure.Persistence.Records.WithdrawalBeneficiaryVersionRecord", b =>
                {
                    b.Property<Guid>("VersionId").HasColumnType("uuid").HasColumnName("version_id");
                    b.Property<DateTimeOffset?>("AvailableAfter").HasColumnType("timestamp with time zone").HasColumnName("available_after");
                    b.Property<Guid>("BeneficiaryId").HasColumnType("uuid").HasColumnName("beneficiary_id");
                    b.Property<string>("BlockReason").HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("block_reason");
                    b.Property<DateTimeOffset?>("BlockedAt").HasColumnType("timestamp with time zone").HasColumnName("blocked_at");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<Guid>("CustomerId").HasColumnType("uuid").HasColumnName("customer_id");
                    b.Property<string>("DestinationHash").IsRequired().HasColumnType("character(64)").HasColumnName("destination_hash");
                    b.Property<string>("RevocationReason").HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("revocation_reason");
                    b.Property<DateTimeOffset?>("RevokedAt").HasColumnType("timestamp with time zone").HasColumnName("revoked_at");
                    b.Property<string>("State").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("state");
                    b.Property<string>("VerificationEvidenceReference").HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("verification_evidence_reference");
                    b.Property<DateTimeOffset?>("VerifiedAt").HasColumnType("timestamp with time zone").HasColumnName("verified_at");
                    b.Property<int>("VersionNumber").HasColumnType("integer").HasColumnName("version_number");
                    b.HasKey("VersionId").HasName("pk_withdrawal_beneficiary_version");
                    b.HasAlternateKey("VersionId", "CustomerId", "DestinationHash").HasName("ak_withdrawal_beneficiary_binding");
                    b.HasIndex("BeneficiaryId", "VersionNumber").IsUnique().HasDatabaseName("ux_withdrawal_beneficiary_version");
                    b.HasIndex("CustomerId", "State").HasDatabaseName("ix_withdrawal_beneficiary_customer_state");
                    b.ToTable("withdrawal_beneficiary_version", "funding", t =>
                        {
                            t.HasCheckConstraint("ck_withdrawal_beneficiary_block_pair", "(blocked_at IS NULL AND block_reason IS NULL) OR (blocked_at IS NOT NULL AND block_reason IS NOT NULL AND btrim(block_reason) <> '')");
                            t.HasCheckConstraint("ck_withdrawal_beneficiary_destination_hash", "destination_hash ~ '^[0-9A-F]{64}$'");
                            t.HasCheckConstraint("ck_withdrawal_beneficiary_identifiers", "version_id <> '00000000-0000-0000-0000-000000000000'::uuid AND beneficiary_id <> '00000000-0000-0000-0000-000000000000'::uuid AND customer_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                            t.HasCheckConstraint("ck_withdrawal_beneficiary_revocation_pair", "(revoked_at IS NULL AND revocation_reason IS NULL) OR (revoked_at IS NOT NULL AND revocation_reason IS NOT NULL AND btrim(revocation_reason) <> '')");
                            t.HasCheckConstraint("ck_withdrawal_beneficiary_state", "state IN ('pending_verification', 'verified_cooling_off', 'active', 'blocked', 'revoked')");
                            t.HasCheckConstraint("ck_withdrawal_beneficiary_state_evidence", "(state = 'pending_verification' AND verification_evidence_reference IS NULL AND blocked_at IS NULL AND revoked_at IS NULL) OR (state IN ('verified_cooling_off', 'active') AND verification_evidence_reference IS NOT NULL AND blocked_at IS NULL AND revoked_at IS NULL) OR (state = 'blocked' AND blocked_at IS NOT NULL AND revoked_at IS NULL) OR (state = 'revoked' AND revoked_at IS NOT NULL)");
                            t.HasCheckConstraint("ck_withdrawal_beneficiary_transition_chronology", "(blocked_at IS NULL OR blocked_at >= created_at) AND (revoked_at IS NULL OR revoked_at >= created_at) AND (blocked_at IS NULL OR revoked_at IS NULL OR revoked_at >= blocked_at)");
                            t.HasCheckConstraint("ck_withdrawal_beneficiary_verification_chronology", "verified_at IS NULL OR (verified_at >= created_at AND available_after >= verified_at)");
                            t.HasCheckConstraint("ck_withdrawal_beneficiary_verification_evidence", "(verification_evidence_reference IS NULL AND verified_at IS NULL AND available_after IS NULL) OR (verification_evidence_reference IS NOT NULL AND btrim(verification_evidence_reference) <> '' AND verified_at IS NOT NULL AND available_after IS NOT NULL)");
                            t.HasCheckConstraint("ck_withdrawal_beneficiary_version_number", "version_number > 0");
                        });
                });

            modelBuilder.Entity("Klyvesta.Infrastructure.Persistence.Records.WithdrawalRequestRecord", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<decimal>("Amount").HasColumnType("numeric(24,8)").HasColumnName("amount");
                    b.Property<DateTimeOffset?>("ApprovedAt").HasColumnType("timestamp with time zone").HasColumnName("approved_at");
                    b.Property<Guid?>("ApprovedByPrincipalId").HasColumnType("uuid").HasColumnName("approved_by_principal_id");
                    b.Property<Guid?>("AuthorizationId").HasColumnType("uuid").HasColumnName("authorization_id");
                    b.Property<Guid>("BeneficiaryVersionId").HasColumnType("uuid").HasColumnName("beneficiary_version_id");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("Currency").IsRequired().HasColumnType("character(3)").HasColumnName("currency");
                    b.Property<Guid>("CustomerId").HasColumnType("uuid").HasColumnName("customer_id");
                    b.Property<string>("DestinationHash").IsRequired().HasColumnType("character(64)").HasColumnName("destination_hash");
                    b.Property<string>("ExternalReference").HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("external_reference");
                    b.Property<string>("OutcomeEvidenceReference").HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("outcome_evidence_reference");
                    b.Property<string>("ReasonCode").HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("reason_code");
                    b.Property<Guid>("RequestedByPrincipalId").HasColumnType("uuid").HasColumnName("requested_by_principal_id");
                    b.Property<string>("State").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("state");
                    b.Property<string>("TransactionDataHash").IsRequired().HasColumnType("character(64)").HasColumnName("transaction_data_hash");
                    b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                    b.HasKey("Id").HasName("pk_withdrawal");
                    b.HasAlternateKey("Id", "RequestedByPrincipalId", "TransactionDataHash").HasName("ak_withdrawal_request_authorization_binding");
                    b.HasIndex("AuthorizationId", "Id").HasDatabaseName("ix_withdrawal_selected_authorization").HasFilter("authorization_id IS NOT NULL");
                    b.HasIndex("BeneficiaryVersionId", "CustomerId", "DestinationHash").HasDatabaseName("ix_withdrawal_beneficiary_binding");
                    b.HasIndex("CustomerId", "State", "CreatedAt").HasDatabaseName("ix_withdrawal_customer_state_created_at");
                    b.ToTable("withdrawal", "funding", t =>
                        {
                            t.HasCheckConstraint("ck_withdrawal_amount", "amount > 0");
                            t.HasCheckConstraint("ck_withdrawal_approval_pair", "(approved_by_principal_id IS NULL AND approved_at IS NULL) OR (approved_by_principal_id IS NOT NULL AND approved_at IS NOT NULL AND approved_at >= created_at AND approved_by_principal_id <> requested_by_principal_id)");
                            t.HasCheckConstraint("ck_withdrawal_authorization_state", "(state IN ('requested', 'security_check', 'security_hold', 'policy_check', 'rejected', 'approval_pending', 'approved') AND authorization_id IS NULL) OR (state IN ('submission_pending', 'submitted', 'processing', 'completed', 'failed', 'unknown') AND authorization_id IS NOT NULL)");
                            t.HasCheckConstraint("ck_withdrawal_chronology", "updated_at >= created_at");
                            t.HasCheckConstraint("ck_withdrawal_currency", "currency ~ '^[A-Z]{3}$'");
                            t.HasCheckConstraint("ck_withdrawal_external_reference", "(external_reference IS NULL OR btrim(external_reference) <> '') AND (state NOT IN ('submitted', 'processing') OR external_reference IS NOT NULL)");
                            t.HasCheckConstraint("ck_withdrawal_hashes", "destination_hash ~ '^[0-9A-F]{64}$' AND transaction_data_hash ~ '^[0-9A-F]{64}$'");
                            t.HasCheckConstraint("ck_withdrawal_identifiers", "id <> '00000000-0000-0000-0000-000000000000'::uuid AND customer_id <> '00000000-0000-0000-0000-000000000000'::uuid AND beneficiary_version_id <> '00000000-0000-0000-0000-000000000000'::uuid AND requested_by_principal_id <> '00000000-0000-0000-0000-000000000000'::uuid AND (approved_by_principal_id IS NULL OR approved_by_principal_id <> '00000000-0000-0000-0000-000000000000'::uuid) AND (authorization_id IS NULL OR authorization_id <> '00000000-0000-0000-0000-000000000000'::uuid)");
                            t.HasCheckConstraint("ck_withdrawal_outcome_evidence", "(state IN ('completed', 'failed') AND outcome_evidence_reference IS NOT NULL AND btrim(outcome_evidence_reference) <> '') OR (state NOT IN ('completed', 'failed') AND outcome_evidence_reference IS NULL)");
                            t.HasCheckConstraint("ck_withdrawal_reason_content", "reason_code IS NULL OR btrim(reason_code) <> ''");
                            t.HasCheckConstraint("ck_withdrawal_reason_required", "state NOT IN ('security_hold', 'rejected', 'failed', 'unknown') OR reason_code IS NOT NULL");
                            t.HasCheckConstraint("ck_withdrawal_state", "state IN ('requested', 'security_check', 'security_hold', 'policy_check', 'rejected', 'approval_pending', 'approved', 'submission_pending', 'submitted', 'processing', 'completed', 'failed', 'unknown')");
                        });
                });

            modelBuilder.Entity("Klyvesta.Infrastructure.Persistence.Records.SecuritySessionRecord", b =>
                {
                    b.HasOne("Klyvesta.Infrastructure.Persistence.Records.SecurityDeviceRecord", null)
                        .WithMany()
                        .HasForeignKey("DeviceId", "PrincipalId", "PrincipalType")
                        .HasPrincipalKey("Id", "PrincipalId", "PrincipalType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_security_session_device_identity");
                });

            modelBuilder.Entity("Klyvesta.Infrastructure.Persistence.Records.WithdrawalAuthorizationRecord", b =>
                {
                    b.HasOne("Klyvesta.Infrastructure.Persistence.Records.SecuritySessionRecord", null)
                        .WithMany()
                        .HasForeignKey("SessionId", "PrincipalId")
                        .HasPrincipalKey("Id", "PrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_withdrawal_authorization_session_principal");

                    b.HasOne("Klyvesta.Infrastructure.Persistence.Records.WithdrawalRequestRecord", null)
                        .WithMany()
                        .HasForeignKey("WithdrawalId", "PrincipalId", "TransactionDataHash")
                        .HasPrincipalKey("Id", "RequestedByPrincipalId", "TransactionDataHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_withdrawal_authorization_request_binding");
                });

            modelBuilder.Entity("Klyvesta.Infrastructure.Persistence.Records.WithdrawalRequestRecord", b =>
                {
                    b.HasOne("Klyvesta.Infrastructure.Persistence.Records.WithdrawalAuthorizationRecord", null)
                        .WithMany()
                        .HasForeignKey("AuthorizationId", "Id")
                        .HasPrincipalKey("Id", "WithdrawalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_withdrawal_selected_authorization");

                    b.HasOne("Klyvesta.Infrastructure.Persistence.Records.WithdrawalBeneficiaryVersionRecord", null)
                        .WithMany()
                        .HasForeignKey("BeneficiaryVersionId", "CustomerId", "DestinationHash")
                        .HasPrincipalKey("VersionId", "CustomerId", "DestinationHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_withdrawal_beneficiary_binding");
                });
#pragma warning restore 612, 618
        }
    }
}
