// <auto-generated />
using System;
using Klyvesta.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Klyvesta.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KlyvestaDbContext))]
    partial class KlyvestaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Klyvesta.Infrastructure.Persistence.Records.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<DateTimeOffset?>("CompletedAt").HasColumnType("timestamp with time zone").HasColumnName("completed_at");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<DateTimeOffset>("ExpiresAt").HasColumnType("timestamp with time zone").HasColumnName("expires_at");
                    b.Property<string>("Key").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("key");
                    b.Property<Guid?>("OperationId").HasColumnType("uuid").HasColumnName("operation_id");
                    b.Property<string>("RequestHash").IsRequired().HasColumnType("character(64)").HasColumnName("request_hash");
                    b.Property<string>("Scope").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("scope");
                    b.Property<string>("State").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("state");
                    b.HasKey("Id").HasName("pk_idempotency_record");
                    b.HasIndex("ExpiresAt").HasDatabaseName("ix_idempotency_record_expires_at");
                    b.HasIndex("Scope", "Key").IsUnique().HasDatabaseName("ux_idempotency_record_scope_key");
                    b.ToTable("idempotency_record", "ops", t =>
                        {
                            t.HasCheckConstraint("ck_idempotency_record_completion_chronology", "completed_at IS NULL OR completed_at >= created_at");
                            t.HasCheckConstraint("ck_idempotency_record_expiry", "expires_at > created_at");
                            t.HasCheckConstraint("ck_idempotency_record_state", "state IN ('in_progress', 'completed', 'failed')");
                        });
                });

            modelBuilder.Entity("Klyvesta.Infrastructure.Persistence.Records.InboxMessage", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<string>("MessageId").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("message_id");
                    b.Property<string>("PayloadHash").IsRequired().HasColumnType("character(64)").HasColumnName("payload_hash");
                    b.Property<string>("PayloadJson").IsRequired().HasColumnType("jsonb").HasColumnName("payload_json");
                    b.Property<DateTimeOffset?>("ProcessedAt").HasColumnType("timestamp with time zone").HasColumnName("processed_at");
                    b.Property<string>("Provider").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("provider");
                    b.Property<DateTimeOffset>("ReceivedAt").HasColumnType("timestamp with time zone").HasColumnName("received_at");
                    b.Property<string>("State").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("state");
                    b.HasKey("Id").HasName("pk_inbox_message");
                    b.HasIndex("Provider", "MessageId").IsUnique().HasDatabaseName("ux_inbox_message_provider_message_id");
                    b.HasIndex("State", "ReceivedAt").HasDatabaseName("ix_inbox_message_state_received_at");
                    b.ToTable("inbox_message", "ops", t =>
                        {
                            t.HasCheckConstraint("ck_inbox_message_processing_chronology", "processed_at IS NULL OR processed_at >= received_at");
                            t.HasCheckConstraint("ck_inbox_message_state", "state IN ('received', 'processing', 'processed', 'failed')");
                        });
                });

            modelBuilder.Entity("Klyvesta.Infrastructure.Persistence.Records.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<int>("AttemptCount").HasColumnType("integer").HasColumnName("attempt_count");
                    b.Property<string>("EventType").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("event_type");
                    b.Property<string>("HeadersJson").HasColumnType("jsonb").HasColumnName("headers_json");
                    b.Property<string>("LastErrorCode").HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("last_error_code");
                    b.Property<DateTimeOffset?>("NextAttemptAt").HasColumnType("timestamp with time zone").HasColumnName("next_attempt_at");
                    b.Property<DateTimeOffset>("OccurredAt").HasColumnType("timestamp with time zone").HasColumnName("occurred_at");
                    b.Property<string>("PayloadJson").IsRequired().HasColumnType("jsonb").HasColumnName("payload_json");
                    b.Property<DateTimeOffset?>("PublishedAt").HasColumnType("timestamp with time zone").HasColumnName("published_at");
                    b.HasKey("Id").HasName("pk_outbox");
                    b.HasIndex("NextAttemptAt", "OccurredAt").HasDatabaseName("ix_outbox_pending").HasFilter("published_at IS NULL");
                    b.ToTable("outbox", "notification", t =>
                        {
                            t.HasCheckConstraint("ck_outbox_attempt_count", "attempt_count >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
