<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Klyvesta.Security.Tests</RootNamespace>
    <AssemblyName>Klyvesta.Security.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" PrivateAssets="all" />
    <PackageReference Include="MSTest.TestAdapter" PrivateAssets="all" />
    <PackageReference Include="MSTest.TestFramework" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Klyvesta.Domain/Klyvesta.Domain.csproj" />
  </ItemGroup>
</Project>
