<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Klyvesta.Domain</RootNamespace>
    <AssemblyName>Klyvesta.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <!-- Entity Framework / PostgreSQL -->
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
</Project>
