using Klyvesta.Domain.Entities;
using Klyvesta.Domain.Services;
using Microsoft.Extensions.Logging;

namespace Klyvesta.Infrastructure.Services;

/// <summary>
/// Implementation of compliance gate for regulatory checks.
/// Enforces mandate requirements and eligibility rules.
/// </summary>
public sealed class ComplianceGate : IComplianceGate
{
    private readonly ILogger<ComplianceGate> _logger;

    public ComplianceGate(ILogger<ComplianceGate> logger)
    {
        _logger = logger;
    }

    public Task<ComplianceCheckResult> CheckAsync(OrderIntent order, CustomerComplianceStatus status, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        // Check 1: Account hold status
        if (status.IsOnHold)
        {
            _logger.LogWarning(
                "Order {OrderId} denied: Customer {CustomerId} account on hold - {Reason}",
                order.Id, status.CustomerId, status.HoldReason);
            return Task.FromResult(ComplianceCheckResult.Denied(
                $"Account on hold: {status.HoldReason ?? "Unspecified reason"}"));
        }

        // Check 2: Mandate requirement for auto orders
        if (order.IsAutoGenerated && !status.HasValidMandate)
        {
            _logger.LogWarning(
                "Order {OrderId} denied: Customer {CustomerId} has no valid mandate for auto-trading",
                order.Id, status.CustomerId);
            return Task.FromResult(ComplianceCheckResult.Denied(
                "No valid mandate for auto-trading operations"));
        }

        // Check 3: Mandate expiry
        if (order.IsAutoGenerated && status.MandateExpiryUtc.HasValue)
        {
            if (status.MandateExpiryUtc.Value <= DateTime.UtcNow)
            {
                _logger.LogWarning(
                    "Order {OrderId} denied: Customer {CustomerId} mandate expired at {ExpiryUtc}",
                    order.Id, status.CustomerId, status.MandateExpiryUtc.Value);
                return Task.FromResult(ComplianceCheckResult.Denied(
                    "Mandate has expired"));
            }
        }

        // Check 4: Operation eligibility
        if (!status.IsEligibleForRequestedOperation)
        {
            _logger.LogWarning(
                "Order {OrderId} denied: Customer {CustomerId} not eligible for requested operation",
                order.Id, status.CustomerId);
            return Task.FromResult(ComplianceCheckResult.Denied(
                "Customer not eligible for requested operation type"));
        }

        // Check 5: Restricted symbols
        if (!string.IsNullOrWhiteSpace(status.RestrictedSymbols))
        {
            var restrictedSymbols = status.RestrictedSymbols
                .Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .Select(s => s.ToUpperInvariant())
                .ToHashSet();

            if (restrictedSymbols.Contains(order.Symbol.Value.ToUpperInvariant()))
            {
                _logger.LogWarning(
                    "Order {OrderId} denied: Symbol {Symbol} is restricted for customer {CustomerId}",
                    order.Id, order.Symbol.Value, status.CustomerId);
                return Task.FromResult(ComplianceCheckResult.Denied(
                    $"Symbol {order.Symbol.Value} is restricted for this customer"));
            }
        }

        _logger.LogInformation(
            "Order {OrderId} passed all compliance checks for customer {CustomerId}",
            order.Id, status.CustomerId);

        return Task.FromResult(ComplianceCheckResult.Approved());
    }
}
