using Klyvesta.Domain.Entities;
using Klyvesta.Domain.Services;
using Klyvesta.Domain.ValueObjects;
using Microsoft.Extensions.Logging;

namespace Klyvesta.Infrastructure.Services;

/// <summary>
/// Implementation of risk governor with deterministic limits.
/// AI cannot override these denials.
/// </summary>
public sealed class RiskGovernor : IRiskGovernor
{
    private readonly ILogger<RiskGovernor> _logger;

    public RiskGovernor(ILogger<RiskGovernor> logger)
    {
        _logger = logger;
    }

    public Task<RiskCheckResult> CheckAsync(OrderIntent order, CustomerRiskProfile profile, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        // Check 1: Auto-trading eligibility
        if (order.IsAutoGenerated && !profile.IsEligibleForAutoTrading)
        {
            _logger.LogWarning(
                "Order {OrderId} denied: Customer {CustomerId} not eligible for auto-trading",
                order.Id, order.CustomerId);
            return Task.FromResult(RiskCheckResult.Denied("Customer not eligible for auto-trading"));
        }

        // Check 2: Max order value
        var orderValue = order.Quantity.Amount * order.LimitPrice.Amount;
        if (orderValue > profile.MaxOrderValue.Amount)
        {
            _logger.LogWarning(
                "Order {OrderId} denied: Value {OrderValue} exceeds max {MaxValue}",
                order.Id, orderValue, profile.MaxOrderValue.Amount);
            return Task.FromResult(RiskCheckResult.Denied(
                $"Order value {orderValue} exceeds maximum allowed {profile.MaxOrderValue.Amount}"));
        }

        // Check 3: Concentration limit (for buys only)
        if (order.Side == OrderSide.Buy)
        {
            // This would require current position data - simplified for now
            // In production, this would query PositionService
            _logger.LogDebug(
                "Order {OrderId} concentration check passed (simplified)",
                order.Id);
        }

        // Check 4: Daily turnover limit
        // This would require tracking daily turnover - simplified for now
        _logger.LogDebug(
            "Order {OrderId} daily turnover check passed (simplified)",
            order.Id);

        // Check 5: Total exposure limit
        // This would require current exposure data - simplified for now
        _logger.LogDebug(
            "Order {OrderId} total exposure check passed (simplified)",
            order.Id);

        _logger.LogInformation(
            "Order {OrderId} passed all risk checks for customer {CustomerId}",
            order.Id, order.CustomerId);
        
        return Task.FromResult(RiskCheckResult.Approved());
    }
}
