<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Klyvesta.Api</RootNamespace>
    <AssemblyName>Klyvesta.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Klyvesta.Application/Klyvesta.Application.csproj" />
    <ProjectReference Include="../Klyvesta.Infrastructure/Klyvesta.Infrastructure.csproj" />
  </ItemGroup>
</Project>
